### ISSUE TITLE
[500] input.match is not a function

### ISSUE THREAD

**Issue by angelorc** [harlan-zw/nuxt-site-config#42]
### 🐛 The bug

When I upgrade my nuxt content site to use `nuxt-site-config@3.1.0` I get several errors:

```
✔ Server built in 5716ms                                                                                                              14:20:36
ℹ Initializing prerenderer                                                                                                      nitro 14:20:36
ℹ Prerendering 13 initial routes with crawler                                                                                   nitro 14:20:58
  ├─ /__preview.json (24ms)                                                                                                      nitro 14:20:58
  ├─ /api/content/blog_it/database.sql (33ms)                                                                                    nitro 14:20:58
  ├─ /api/content/landing_it/database.sql (31ms)                                                                                 nitro 14:20:58
  ├─ /api/content/docs_en/database.sql (30ms)                                                                                    nitro 14:20:58
  ├─ /api/content/content_it/database.sql (30ms)                                                                                 nitro 14:20:58
  ├─ /api/content/content_en/database.sql (30ms)                                                                                 nitro 14:20:58
  ├─ /api/content/fantoken_it/database.sql (30ms)                                                                                nitro 14:20:58
  ├─ /api/content/fantoken_en/database.sql (30ms)                                                                                nitro 14:20:58
  ├─ /api/content/landing_en/database.sql (29ms)                                                                                 nitro 14:20:58
  ├─ /api/content/tutorial_it/database.sql (31ms)                                                                                nitro 14:20:58
  ├─ /api/content/blog_en/database.sql (32ms)                                                                                    nitro 14:20:58
  ├─ /api/content/tutorial_en/database.sql (31ms)                                                                                nitro 14:20:58
  ├─ / (476ms)                                                                                                                   nitro 14:20:58

 ERROR  [nuxt] [request error] [unhandled] [500] input.match is not a function                                                         14:20:58
  at withProtocol (./node_modules/.cache/nuxt/.nuxt/prerender/chunks/nitro/nitro.mjs:252:21)  
  at withHttps (./node_modules/.cache/nuxt/.nuxt/prerender/chunks/nitro/nitro.mjs:246:10)  
  at normalizeSiteConfig (./node_modules/.cache/nuxt/.nuxt/prerender/chunks/nitro/nitro.mjs:685:18)  
  at Object.get (./node_modules/.cache/nuxt/.nuxt/prerender/chunks/nitro/nitro.mjs:740:51)  
  at useSiteConfig (./node_modules/.cache/nuxt/.nuxt/prerender/chunks/nitro/nitro.mjs:759:31)  
  at createSitePathResolver (./node_modules/.cache/nuxt/.nuxt/prerender/chunks/nitro/nitro.mjs:2612:22)  
  at ./node_modules/.cache/nuxt/.nuxt/prerender/chunks/nitro/nitro.mjs:3286:33  
  at ./node_modules/.pnpm/hookable@5.5.3/node_modules/hookable/dist/index.mjs:48:66  
  at ./node_modules/.pnpm/hookable@5.5.3/node_modules/hookable/dist/index.mjs:48:56  
  at async Object.render (./node_modules/.cache/nuxt/.nuxt/prerender/chunks/_/renderer3.mjs:386:3)
```

This happen only when upgrade nuxt-site-config to 3.1.0

### 🛠️ To reproduce

-

### 🌈 Expected behavior

Should work as previous releases

**Comment by harlan-zw** [comment]
Hmm strange, I think I'd need a reproduction to fix this properly. 

The related logic is here:

```ts
  if (config.url && !hasProtocol(config.url, { acceptRelative: true, strict: false }))
    config.url = withHttps(config.url)
```

So it seems like you're passing something isn't a string (?) as the site URL. I've pushed a fix to normalize the URL as a string but you may ran into issues still.

You can upgrade using `nuxi upgrade --force`
